owner: MitsMediaClub
repo: status

sites:
  - name: GRID Platform
    url: https://grid.mitsmediaclub.com

status-page:
  baseUrl: /status
  title: MITS Media Club Status
  theme: dark 
  logoUrl: https://avatars.githubusercontent.com/u/105416301?s=280&v=4
  navbar:
    - title: Status
      href: /
    - title: Visit GRID
      href: https://grid.mitsmediaclub.com
